### ISSUE TITLE
How to get messages?

### ISSUE THREAD

**Issue by frozenade** [shakedNissanov/WhatsappBot#2]
How to use:

Read all available messages
>> seleniumbot.readAllMessages(targetName, textDirection)

I get:
`[<selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-44")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-45")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-46")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-47")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-48")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-49")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-50")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-51")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-52")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-53")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-54")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-55")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-56")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-57")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-58")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-59")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-60")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-61")>, <selenium.webdriver.remote.webelement.WebElement (session="fab5e831fd5eb60e9e44ddc1c5266980", element="0.6097445617121475-62")>]`

I can't figured 'em out.

**Comment by frozenade** [comment]
>>> readAllMessages('Momy', 'rtl')
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    readAllMessages('Momy', 'rtl')
  File "C:\Python\WhatsappBot.py", line 40, in readAllMessages
    target = driver.find_element_by_xpath('//span[@title= "{}"]'.format(targetName))
AttributeError: 'NoneType' object has no attribute 'find_element_by_xpath'
>>> seleniumbot.readAllMessages('Momy', 'rtl')
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    seleniumbot.readAllMessages('Momy', 'rtl')
  File "C:\Python\Python37\lib\site-packages\seleniumbot\__init__.py", line 55, in readAllMessages
    messages[i] = messages[i][::-1]
TypeError: 'WebElement' object is not subscriptable
